version: '3'

services: 
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: jjnatanx/laravel:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: jjnatanx/nginx:prod
    container_name: mginx
    networks: 
      - laranet
    ports:
      - "8080:80"

networks: 
  laranet:
    driver: bridge