FROM nginx:latest

#USER jonathan

WORKDIR /app

RUN apt-get update && \ 
    apt-get install vim -y

COPY ./ /usr/share/nginx/html
#COPY html/ /usr/share/nginx/html

#RUN apt-get update
#RUN apt-get install vim -y